spring:
  application:
    name: oidc-idp
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  datasource:
    url: jdbc:mysql://localhost:3306/oidc_idp
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: "classpath:db/migration,classpath:db/test"
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  security:
    oauth2:
      resourceserver:
        opaque-token:
          issuer-uri: http://localhost:8080/auth/realms/demo
      client:
        provider:
          demo:
            issuer-uri: http://localhost:8080/auth/realms/demo
        registration:
          demo:
            provider: demo
            client-id: spring-client
            client-secret: changeme
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/demo
